# Generated by Django 6.0.3 on 2026-03-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Customer Name')),
                ('customer_address', models.CharField(blank=True, max_length=500, verbose_name='Customer Address')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Customer Name')),
                ('customer_address', models.CharField(blank=True, max_length=500, verbose_name='Customer Address')),
                ('company', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('equipment', models.CharField(blank=True, max_length=255)),
                ('tested_load', models.CharField(blank=True, max_length=100)),
                ('safe_load', models.CharField(blank=True, max_length=100)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('mechanic', models.CharField(blank=True, max_length=150)),
                ('date_inspection', models.DateField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Load Test',
                'verbose_name_plural': 'Load Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Customer Name')),
                ('customer_address', models.CharField(blank=True, max_length=500, verbose_name='Customer Address')),
                ('record_type', models.CharField(choices=[('repair', 'Repair'), ('inspection', 'Inspection')], default='repair', max_length=20)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('report_number', models.CharField(blank=True, max_length=100)),
                ('mechanic', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('customer_report', models.TextField(blank=True)),
                ('diagnose_result', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Repair / Inspection',
                'verbose_name_plural': 'Repair / Inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True)),
                ('accessories', models.TextField(blank=True)),
                ('date_of_inspection', models.DateField()),
                ('due_next_inspection', models.DateField()),
                ('product_description', models.CharField(max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('working_load_limits', models.CharField(blank=True, max_length=100)),
                ('tested_load', models.CharField(blank=True, max_length=100)),
                ('pressure_relief', models.CharField(blank=True, max_length=100)),
                ('load_cell_certificate_number', models.CharField(blank=True, max_length=100)),
                ('work_perform', models.TextField(blank=True, default='The described equipment was set up and tested in accordance with Tronair and Service Manual. The equipment should only be used in configuration as tested with the total load less than or equal to the rated working load limit.\n\nI hereby certify that the above-described equipment is compatible to meeting the load ratings when used under normal and proper use.')),
                ('technician_name', models.CharField(max_length=150)),
                ('technician_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='core.customer')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestEquipmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('model_no', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_equipment_rows', to='core.certificate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
