# Generated by Django 6.0.3 on 2026-03-17 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loadtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='repairinspection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadtest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loadtest_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repairinspection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='customer_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loadtest',
            name='customer_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='loadtest',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repairinspection',
            name='customer_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='repairinspection',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
