# Generated by Django 6.0.3 on 2026-03-17 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certificate_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadCellSavedCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cert_number'],
            },
        ),
        migrations.CreateModel(
            name='LoadCellCertRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(blank=True, max_length=255, verbose_name='Load Cell Certificate Number')),
                ('order', models.PositiveIntegerField(default=0)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_cell_rows', to='core.certificate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
