# Generated by Django 6.0.3 on 2026-04-10 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loadcellsavedcert_loadcellcertrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='loadcellcertrow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loadtest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='repairinspection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testequipmentrow',
            options={},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loadcellcertrow',
            name='order',
        ),
        migrations.RemoveField(
            model_name='loadcellsavedcert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loadtest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='repairinspection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testequipmentrow',
            name='order',
        ),
        migrations.AddField(
            model_name='inventory',
            name='capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loadtest',
            name='capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repairinspection',
            name='capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='due_next_inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='product_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='technician_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='technician_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='work_perform',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loadcellcertrow',
            name='cert_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loadcellcertrow',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_cell_cert_rows', to='core.certificate'),
        ),
        migrations.AlterField(
            model_name='loadcellsavedcert',
            name='cert_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='loadtest',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loadtest',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loadtest',
            name='mechanic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repairinspection',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repairinspection',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='repairinspection',
            name='mechanic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PhotoReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('loadtest', 'Load Test'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('inventory', 'Inventory'), ('general', 'General')], default='general', max_length=20)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('equipment_name', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
