# Generated by Django 6.0.3 on 2026-04-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_certificate_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='capacity',
            new_name='part_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='less_by',
            field=models.PositiveIntegerField(default=0, help_text='Amount to deduct from current stock'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='use',
            field=models.TextField(blank=True, help_text='Purpose or usage of this item'),
        ),
    ]
